test_that("a collection without _skilldown.yml gets the defaults", {
  src <- local_fixture("collection-basic")
  cfg <- read_config(src)
  expect_true(is.na(cfg$file))
  expect_null(cfg$title)
  expect_null(cfg$url)
  expect_null(cfg$theme)
  expect_null(cfg$news)
  expect_equal(cfg$exclude, character())
  expect_null(cfg$navbar)
  expect_null(cfg$reference)
  expect_null(cfg$articles)
})

test_that("_skilldown.yml is read and validated", {
  src <- local_fixture("collection-configured")
  cfg <- read_config(src)
  expect_equal(cfg$title, "Configured Collection")
  expect_equal(cfg$url, "https://example.org/configured")
  expect_equal(cfg$theme, "flatly")
  expect_equal(cfg$news, "HISTORY.md")
  expect_equal(cfg$exclude, c("skills/gamma", "docs/draft-*.md"))
  expect_equal(cfg$navbar$right[[1]]$text, "Docs")
  expect_equal(cfg$reference[[1]]$title, "Core")
  expect_equal(cfg$reference[[1]]$desc, "The skills to start with.")
  expect_equal(cfg$reference[[2]]$contents, "be*")
  expect_equal(cfg$articles[[1]]$contents, "getting-started")
  expect_equal(cfg$surfaces, list(agents = FALSE))
})

test_that("bootswatch is an alias of theme", {
  src <- local_fixture("collection-basic")
  writeLines("bootswatch: lux", fs::path(src, "_skilldown.yml"))
  expect_equal(read_config(src)$theme, "lux")
  writeLines(c("theme: flatly", "bootswatch: lux"), fs::path(src, "_skilldown.yml"))
  expect_equal(read_config(src)$theme, "flatly")
})

test_that("configuration errors are loud and unknown keys are reported", {
  src <- local_fixture("collection-basic")
  writeLines("title: [unclosed", fs::path(src, "_skilldown.yml"))
  expect_error(read_config(src), "not valid YAML")
  writeLines("- just: a list", fs::path(src, "_skilldown.yml"))
  expect_error(read_config(src), "mapping of keys to values")
  writeLines(c("title: ok", "colour: red"), fs::path(src, "_skilldown.yml"))
  expect_warning(cfg <- read_config(src), "unknown")
  expect_equal(cfg$title, "ok")
  writeLines(c("title:", "  - a", "  - b"), fs::path(src, "_skilldown.yml"))
  expect_error(read_config(src), "single string")
  writeLines(c("navbar:", "  middle: []"), fs::path(src, "_skilldown.yml"))
  expect_error(read_config(src), "left.*right")
  writeLines(c("reference:", "  - desc: no title", "    contents: [alpha]"), fs::path(src, "_skilldown.yml"))
  expect_error(read_config(src), "needs a")
  writeLines(c("reference:", "  - title: Empty"), fs::path(src, "_skilldown.yml"))
  expect_error(read_config(src), "contents")
})

test_that("exclude globs drop skills from discovery", {
  src <- local_fixture("collection-configured")
  found <- discover_skills(src, exclude = c("skills/gamma", "skills/de*"))
  expect_equal(found$rel_dir, c("skills/alpha", "skills/beta"))
  expect_equal(attr(found, "excluded"), c("skills/delta", "skills/gamma"))
  expect_equal(nrow(discover_skills(src)), 4)
})

test_that("generation applies the configuration", {
  x <- generate_fixture("collection-configured")
  m <- x$manifest
  expect_equal(m$title, "Configured Collection")
  expect_setequal(m$skills, c("alpha", "beta", "delta"))
  expect_setequal(m$excluded, c("skills/gamma", "docs/draft-notes.md"))
  expect_true("HISTORY.md" %in% m$pages)
  expect_false("NEWS.md" %in% m$pages)
  expect_false("docs/draft-notes.md" %in% m$pages)
  expect_false(fs::file_exists(fs::path(x$work, "skills", "gamma", "index.md")))
  expect_true(any(grepl("`delta`.*Other skills", m$notes$note)))
  expect_true(any(grepl("docs/advanced.md.*Other articles", m$notes$note)))

  config <- read_work(x, "_quarto.yml")
  expect_match(config, "site-url: https://example.org/configured", fixed = TRUE)
  expect_match(config, "theme: flatly", fixed = TRUE)
  expect_match(config, "icon: bi-clock-history", fixed = TRUE)
  expect_match(config, "text: Docs", fixed = TRUE)
  expect_equal(lengths(regmatches(config, gregexpr("text: News", config))), 1)

  expect_snapshot(cat(config))
  expect_snapshot(cat(read_work(x, "reference/skills.md")))
  expect_snapshot(cat(read_work(x, "reference/articles.md")))
})

test_that("a missing news file falls back with a warning", {
  src <- local_fixture("collection-basic")
  writeLines("news: HISTORY.md", fs::path(src, "_skilldown.yml"))
  work <- fs::path(withr::local_tempdir(), "site")
  expect_warning(m <- generate_site(src, work = work), "does not exist")
  expect_true("NEWS.md" %in% m$pages)
})

test_that("the zero-config site is unchanged by the config layer", {
  x <- generate_fixture("collection-basic")
  expect_equal(x$manifest$excluded, character())
  expect_true(is.na(x$manifest$config$file))
  config <- read_work(x, "_quarto.yml")
  expect_no_match(config, "site-url")
  expect_match(config, "theme: cosmo", fixed = TRUE)
})
